### ISSUE TITLE
Capitalization of search terms

### ISSUE THREAD

**Issue by grezniczek** [biggeeves/dictionary_search#5]
It seems that in the search results, the search string is always shown in capital letters.

Why is this?
I guess to highlight? But then inserting `<span style="background-color:yellow">...</span>` around the match would be more useful, twofold:
- easier to spot
- can view (and copy/paste) the result as it actually is 

The last point is rather important, as sometimes one would like to exclude presence of a capitalization error, e.g. in case-sensitive links, etc.

**Comment by biggeeves** [comment]
I agree.  I toyed with several versions.  I'll release a new version with the text highlighted in yellow.
